name: Lint Dockerfile
on: pull_request
concurrency: # 自動キャンセル
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # タイムアウト
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
      - uses: hadolint/hadolint-action@v3.3.0
        with:
          recursive: true
